# Generated by Django 4.2.9 on 2024-01-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('vat', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_price', models.FloatField()),
                ('gross_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JPK_FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_diagram', models.CharField(max_length=10)),
                ('invoice', models.ManyToManyField(to='jpk_fa_app.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='position',
            field=models.ManyToManyField(to='jpk_fa_app.item'),
        ),
    ]
