# Generated by Django 4.2.9 on 2024-01-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpk_fa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
